backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)

# This line should *not* be indented
publish_mode: editorial_workflow

# This line should *not* be indented
media_folder: '/img' # Media files will be stored in the repo under images/uploads

collections:
  - name: 'post'
    label: 'News'
    folder: 'posts'
    create: true
    slug: '{{ year }}-{{ month }}-{{ day }}-{{ slug }}'
    fields:
      - { label: 'Type', name: 'type', widget: 'hidden', default: 'News' }
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Image', name: 'card_img', widget: 'image' }
      - { label: 'Homepage Image', name: 'card_img_home', widget: 'image' }
      - { label: 'Body', name: 'card_article', widget: 'markdown' }
      - { label: 'Publish Date', name: 'date', widget: 'datetime' }
